# render.yaml — OmniBack (Backend Node + Frontend SPA + Postgres)

databases:
  - name: omniback-db
    plan: starter

services:
  # =========================
  # Backend (Node/Express)
  # =========================
  - type: web
    name: omni-back
    env: node
    plan: starter
    autoDeploy: true
    region: oregon
    rootDir: backend
    buildCommand: "npm ci && npm run build"
    startCommand: "node dist/index.js"
    healthCheckPath: "/health"
    notifyOnFail: true

    envVars:
      # --- Básicos ---
      - key: NODE_ENV
        value: production
      - key: SERVICE_NAME
        value: omni-back

      # --- URLs (ajusta a tus subdominios de Render o tu dominio propio) ---
      - key: BACKEND_URL
        value: https://tubackend.onrender.com
      - key: PUBLIC_URL
        value: https://tufrontend.onrender.com
      - key: ALLOWED_ORIGIN
        value: https://tufrontend.onrender.com,https://<tu-dominio>.com

      # --- Base de datos (se inyecta sola desde la DB de arriba) ---
      - key: DATABASE_URL
        fromDatabase:
          name: omniback-db
          property: connectionString

      # --- Seguridad y JWT (cárgalos como secrets en el dashboard si quieres) ---
      - key: SESSION_SECRET
        value: "<pon_un_valor_largo_y_aleatorio>"
        sync: false
      - key: JWT_SECRET
        value: "<pon_otro_valor_largo_y_aleatorio>"
        sync: false

      # --- Google OAuth ---
      - key: GOOGLE_CLIENT_ID
        value: "<tu_client_id>.apps.googleusercontent.com"
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        value: "<tu_client_secret>"
        sync: false
      - key: GOOGLE_CALLBACK_URL
        value: https://tubackend.onrender.com/auth/google/callback

      # --- Tokens / otros ---
      - key: ACCESS_TOKEN_TTL
        value: "15m"
      - key: REFRESH_TOKEN_TTL_MS
        value: "604800000" # 7 días
      - key: MAX_REQUEST_SIZE
        value: "2mb"

    # Ejecuta migraciones tras cada deploy exitoso (idempotente si tus .sql lo permiten)
    postDeployCommand: >
      bash -lc "
      psql \"$DATABASE_URL\" -f sql/001_init.sql &&
      psql \"$DATABASE_URL\" -f sql/002_multitenant.sql
      "

  # =========================
  # Frontend (SPA estático)
  # =========================
  - type: static
    name: omni-front
    plan: starter
    autoDeploy: true
    region: oregon
    rootDir: frontend
    buildCommand: "npm ci && npm run build"
    publishPath: "build"

    envVars:
      - key: REACT_APP_API_BASE
        value: https://<tu-backend>.onrender.com
      - key: PUBLIC_URL
        value: https://<tu-frontend>.onrender.com

    # Cache suave y fallback SPA
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=300
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
