name: Backend CI & CD (Docker → GHCR)

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci-cd.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "backend/package-lock.json"

      - name: Install deps
        run: npm ci

      - name: Lint (optional)
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script. Skipping."
          fi

      - name: Build TypeScript
        run: npm run build

      - name: Test (optional)
        run: |
          if npm run | grep -q "test"; then
            npm test -- --ci --reporters=default
          else
            echo "No test script. Skipping."
          fi

      - name: Define meta (version/sha/time)
        id: meta
        run: |
          APP_VERSION=$(node -p "require('./package.json').version || '0.0.0'")
          GIT_SHA=$(git rev-parse --short HEAD)
          BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "git_sha=$GIT_SHA" >> $GITHUB_OUTPUT
          echo "build_time=$BUILD_TIME" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          file: ./backend/Dockerfile
          build-args: |
            APP_VERSION=${{ steps.meta.outputs.app_version }}
            GIT_SHA=${{ steps.meta.outputs.git_sha }}
            BUILD_TIME=${{ steps.meta.outputs.build_time }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')-backend:latest
            ghcr.io/${{ github.repository_owner }}/$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')-backend:${{ steps.meta.outputs.git_sha }}
