name: Deploy OmniBack

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Aquí puedes agregar pasos específicos para Render, Railway, etc.
      # Por ejemplo, un deploy script o integración con CLI de plataforma
